### ISSUE TITLE
TouchDesigner Fails - No match found on URL

### ISSUE THREAD

**Issue by kclose3** [autopkg/moofit-recipes#133]
TouchDesigner download fails with the following error:

local.jamf.TouchDesigner
        Error in local.jamf.TouchDesigner: Processor: URLTextSearcher: Error: No match found on URL: https://derivative.ca/download

**Comment by pnerum** [comment]
There's a pull request pending for some recipe changes: https://github.com/autopkg/moofit-recipes/pull/132
