### ISSUE TITLE
No match found on URL

### ISSUE THREAD

**Issue by cstout1** [autopkg/moofit-recipes#20]
EgnyteConnect.Download & EgnyteConnect.pkg produce:
`No match found on URL: https://helpdesk.egnyte.com/hc/en-us/articles/205237150-Desktop-App-Installers`

Also, I'm not certain if "EgnyteConnect.pkg" was for a previously hosted dmg, but Egnyte is hosting a deployable pkg at: https://egnyte-cdn.egnyte.com/egnytedrive/mac/en-us/3.2.1/EgnyteConnect_3.2.1_202101.pkg

Edit: Sorry, it's early. I see the pkg recipe just appears to rename the downloaded pkg from the download recipe. Reported error is still true but note about "previously hosted dmg" is irrelevant.

**Comment by wegotoeleven** [comment]
Fixed. They switched from HTTP to HTTPS.
