### ISSUE TITLE
EgnyteConnect.pkg does not list version number

### ISSUE THREAD

**Issue by cstout1** [autopkg/moofit-recipes#22]
EgnyteConnect.pkg, when run through autopkgr, does not provide a version number whereas EgnyteConnect.download does. Every report e-mailed after running autopkgr provides the following:

NAME | VERSION
Egnyte Connect | Unknown version

The following new items were downloaded:
/var/user/Library/AutoPkg/Cache/local.pkg.EgnyteConnect/downloads/Egnyte Connect.pkg

**Comment by macmule** [comment]
@cstout1 old issue.. but this seems to have been resolved prior.. if not then it should be resolved in - https://github.com/autopkg/moofit-recipes/pull/63

**Comment by wegotoeleven** [comment]
Resolved indeed!
