### ISSUE TITLE
Opera.pkg.recipe only retrieves a partial version number

### ISSUE THREAD

**Issue by beatlemike** [autopkg/moofit-recipes#24]
Opera.pkg.recipe only retrieves a partial version number. ie v60.0, while there have been 5 versions of 60.0 for Mac.

60.0.3255.27
60.0.3255.56
60.0.3255.59
60.0.3255.70
60.0.3255.83

**Comment by wegotoeleven** [comment]
I have changed the parent recipe to the Opera recipe in Bochoven's recipe repo; this should now work!

**Comment by beatlemike** [comment]
Awesome thanks!
