### ISSUE TITLE
mirrorop download recipe issue

### ISSUE THREAD

**Issue by ewtillman** [autopkg/moofit-recipes#35]
Looks like http://mirrorop.com/ is no longer maintained and moved over to barco.com.
That being said the link in your mirrop download recipe is no longer getting the latest versions.
Last version on the old mirrop site is 2.3.0 and on barco its up to 2.5.0.

**Comment by neilmartin83** [comment]
Opened a PR to fix this: https://github.com/autopkg/moofit-recipes/pull/41
