### ISSUE TITLE
Media Human - Website Down

### ISSUE THREAD

**Issue by paul-cossey** [autopkg/moofit-recipes#67]
The AudioConverter.download.recipe is currently failing due to Media Humans website being down. It was last seen up around 8 hours ago. 

https://www.mediahuman.com

Processor: URLDownloader: Error: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://www.mediahuman.com/download/MHAudioConverter.dmg', '--fail', '--output',  returned non-zero exit status 6.

**Comment by wegotoeleven** [comment]
Fixed with https://github.com/autopkg/moofit-recipes/pull/68
