### ISSUE TITLE
ClickShare.download deletes RECIPE_CACHE_DIR

### ISSUE THREAD

**Issue by grahampugh** [autopkg/moofit-recipes#70]
The `ClickShare.download` recipe contains a `PathDeleter` processor at the start that deletes the entire `RECIPE_CACHE_DIR`. That's weird, and breaks my automations which rely on the receipts or other files I store in the cache.

I'm not sure why this is done, but I presume it's to remove any existing downloads or packages. Those should be handled in the relevant processors, which have appropriate arguments to handle this.

**Comment by wegotoeleven** [comment]
This was added to fix an issue where subsequent runs of the recipe failed when the downloaded file remained in the `downloads` folder.

It appears that the the server presents a 400 error when the curl command includes `ETag` or `Last-Modified` headers. Using a `CHECK_FILESIZE_ONLY` value of `true` in the `URLDownloader` processor didn't work either (at least in my testing, and I could be doing something wrong!) as it still included `ETag` and `Last-Modified` headers.

We also tried to solely delete the `downloads` folder that's created inside the `RECIPE_CACHE_DIR` folder, but if the folder isn't there, the recipe fails.

I hope this makes sense! Please feel free to drop some suggestions if you have them, or if you see anything obvious that's wrong with the recipe, please let me know.

**Comment by grahampugh** [comment]
Would it be possible to just delete the contents of the downloads folder without deleting the folder itself? Presumably the filetype of the download is predictable so you could just delete files with the expected suffixes.

**Comment by wegotoeleven** [comment]
Sorry about this! We now use the path to the zip file itself, and we use a new FriendlyPathDeleter processor to delete the file, and _not_ fail out if the file doesn't exist. Should work now!

https://github.com/autopkg/moofit-recipes/commit/8fd8e7d61b4b1c1cba680a107dd968ffdbb6cb5a

**Comment by wegotoeleven** [comment]
@grahampugh When you get a sec, can you give this new recipe a try and sit if it fits the bill for you? <3

**Comment by grahampugh** [comment]
Looks fine now, thanks!
