### ISSUE TITLE
Sketch.pkg.recipe recipe fails the download with a curl error 6

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/moofit-recipes#85]
The URL is hardcoded to https://github.com/autopkg/moofit-recipes/blob/master/Sketch/Sketch.pkg.recipe#L24 which returns an error in Safari too. The new URL looks to be `https://www.sketch.com/download/sketch.zip`.
PR Incoming...

**Comment by wegotoeleven** [comment]
Merged! Thanks @Daz-wallace
