### ISSUE TITLE
MicrosoftTeams.pkg.recipe is using existing identifier from another repo

### ISSUE THREAD

**Issue by grahampugh** [autopkg/moofit-recipes#99]
It looks like you copied Rich Trouton's recipe and did not change the identifier (`com.github.rtrouton.pkg.microsoftteams`), so your recipe is hijacking his. Please change the identifier to a moofit-recipes one.

PS It seems like the only reason you have done this is to override the bundle identifier which arguably could be done in your private overrides rather than creating another Teams recipe in the AutoPkg org.

**Comment by fmamberti** [comment]
Hi Graham, thanks for flagging this. We will update this soon.
